package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cotizaciones generated by hbm2java
 */
@Entity
@Table(name="Cotizaciones"
    ,catalog="cosw2"
)
public class Cotizacion  implements java.io.Serializable {


     private int idCotizaciones;
     private Medicamento medicamentos;
     private Proveedor proveedores;
     private Integer cantidad;
     private Integer precio;

    public Cotizacion() {
    }

	
    public Cotizacion(int idCotizaciones) {
        this.idCotizaciones = idCotizaciones;
    }
    public Cotizacion(int idCotizaciones, Medicamento medicamentos, Proveedor proveedores, Integer cantidad, Integer precio) {
       this.idCotizaciones = idCotizaciones;
       this.medicamentos = medicamentos;
       this.proveedores = proveedores;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
     @Id 
    @Column(name="idCotizaciones", unique=true, nullable=false)
    public int getIdCotizaciones() {
        return this.idCotizaciones;
    }
    
    public void setIdCotizaciones(int idCotizaciones) {
        this.idCotizaciones = idCotizaciones;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Medicamento")
    public Medicamento getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Medicamento medicamentos) {
        this.medicamentos = medicamentos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Proveedor")
    public Proveedor getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedor proveedores) {
        this.proveedores = proveedores;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="Precio")
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


