package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Devoluciones generated by hbm2java
 */
@Entity
@Table(name="Devoluciones"
    ,catalog="cosw2"
)
public class Devolucion  implements java.io.Serializable {


     private int idDevoluciones;
     private MedicamentoPorProveedor medicamentosPorProveedor;
     private OrdenCompra ordenesCompra;

    public Devolucion() {
    }

	
    public Devolucion(int idDevoluciones) {
        this.idDevoluciones = idDevoluciones;
    }
    public Devolucion(int idDevoluciones, MedicamentoPorProveedor medicamentosPorProveedor, OrdenCompra ordenesCompra) {
       this.idDevoluciones = idDevoluciones;
       this.medicamentosPorProveedor = medicamentosPorProveedor;
       this.ordenesCompra = ordenesCompra;
    }
   
     @Id 

    
    @Column(name="idDevoluciones", unique=true, nullable=false)
    public int getIdDevoluciones() {
        return this.idDevoluciones;
    }
    
    public void setIdDevoluciones(int idDevoluciones) {
        this.idDevoluciones = idDevoluciones;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MedicamentoPorProveedor")
    public MedicamentoPorProveedor getMedicamentosPorProveedor() {
        return this.medicamentosPorProveedor;
    }
    
    public void setMedicamentosPorProveedor(MedicamentoPorProveedor medicamentosPorProveedor) {
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OrdenCompra")
    public OrdenCompra getOrdenesCompra() {
        return this.ordenesCompra;
    }
    
    public void setOrdenesCompra(OrdenCompra ordenesCompra) {
        this.ordenesCompra = ordenesCompra;
    }




}


