package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicamentosPorProveedor generated by hbm2java
 */
@Entity
@Table(name="MedicamentosPorProveedor"
    ,catalog="cosw2"
)
public class MedicamentoPorProveedor  implements java.io.Serializable {


     private int idMedicamentosProvedor;
     private Medicamento medicamentos;
     private Proveedor proveedores;
     private Integer precio;
     private Set<Devolucion> devolucioneses = new HashSet<Devolucion>(0);
     private Set<ItemDeFactura> itemsDeFacturas = new HashSet<ItemDeFactura>(0);
     private Set<DetalleOrdenCompra> detallesOrdenesCompras = new HashSet<DetalleOrdenCompra>(0);
     private Set<DetallePedido> detallesPedidos = new HashSet<DetallePedido>(0);
     private Set<DetalleInventario> detalleInventarios = new HashSet<DetalleInventario>(0);

    public MedicamentoPorProveedor() {
    }

	
    public MedicamentoPorProveedor(int idMedicamentosProvedor, Medicamento medicamentos, Proveedor proveedores) {
        this.idMedicamentosProvedor = idMedicamentosProvedor;
        this.medicamentos = medicamentos;
        this.proveedores = proveedores;
    }
    public MedicamentoPorProveedor(int idMedicamentosProvedor, Medicamento medicamentos, Proveedor proveedores, Integer precio, Set<Devolucion> devolucioneses, Set<ItemDeFactura> itemsDeFacturas, Set<DetalleOrdenCompra> detallesOrdenesCompras, Set<DetallePedido> detallesPedidos, Set<DetalleInventario> detalleInventarios) {
       this.idMedicamentosProvedor = idMedicamentosProvedor;
       this.medicamentos = medicamentos;
       this.proveedores = proveedores;
       this.precio = precio;
       this.devolucioneses = devolucioneses;
       this.itemsDeFacturas = itemsDeFacturas;
       this.detallesOrdenesCompras = detallesOrdenesCompras;
       this.detallesPedidos = detallesPedidos;
       this.detalleInventarios = detalleInventarios;
    }
   
     @Id 

    
    @Column(name="idMedicamentosProvedor", unique=true, nullable=false)
    public int getIdMedicamentosProvedor() {
        return this.idMedicamentosProvedor;
    }
    
    public void setIdMedicamentosProvedor(int idMedicamentosProvedor) {
        this.idMedicamentosProvedor = idMedicamentosProvedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMedicamentos", nullable=false)
    public Medicamento getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Medicamento medicamentos) {
        this.medicamentos = medicamentos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProveedores", nullable=false)
    public Proveedor getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedor proveedores) {
        this.proveedores = proveedores;
    }

    
    @Column(name="Precio")
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set<Devolucion> getDevolucioneses() {
        return this.devolucioneses;
    }
    
    public void setDevolucioneses(Set<Devolucion> devolucioneses) {
        this.devolucioneses = devolucioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set<ItemDeFactura> getItemsDeFacturas() {
        return this.itemsDeFacturas;
    }
    
    public void setItemsDeFacturas(Set<ItemDeFactura> itemsDeFacturas) {
        this.itemsDeFacturas = itemsDeFacturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set<DetalleOrdenCompra> getDetallesOrdenesCompras() {
        return this.detallesOrdenesCompras;
    }
    
    public void setDetallesOrdenesCompras(Set<DetalleOrdenCompra> detallesOrdenesCompras) {
        this.detallesOrdenesCompras = detallesOrdenesCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set<DetallePedido> getDetallesPedidos() {
        return this.detallesPedidos;
    }
    
    public void setDetallesPedidos(Set<DetallePedido> detallesPedidos) {
        this.detallesPedidos = detallesPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set<DetalleInventario> getDetalleInventarios() {
        return this.detalleInventarios;
    }
    
    public void setDetalleInventarios(Set<DetalleInventario> detalleInventarios) {
        this.detalleInventarios = detalleInventarios;
    }




}


