package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenesCompra generated by hbm2java
 */
@Entity
@Table(name="OrdenesCompra"
    ,catalog="cosw2"
)
public class OrdenCompra  implements java.io.Serializable {


     private Integer idOrdenesCompra;
     private Date fecha;
     private Set<DetalleOrdenCompra> detallesOrdenesCompras = new HashSet<DetalleOrdenCompra>(0);
     private Set<Devolucion> devolucioneses = new HashSet<Devolucion>(0);

    public OrdenCompra() {
    }

	
    public OrdenCompra(Date fecha) {
        this.fecha = fecha;
    }
    public OrdenCompra(Date fecha, Set<DetalleOrdenCompra> detallesOrdenesCompras, Set<Devolucion> devolucioneses) {
       this.fecha = fecha;
       this.detallesOrdenesCompras = detallesOrdenesCompras;
       this.devolucioneses = devolucioneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idOrdenesCompra", unique=true, nullable=false)
    public Integer getIdOrdenesCompra() {
        return this.idOrdenesCompra;
    }
    
    public void setIdOrdenesCompra(Integer idOrdenesCompra) {
        this.idOrdenesCompra = idOrdenesCompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenesCompra")
    public Set<DetalleOrdenCompra> getDetallesOrdenesCompras() {
        return this.detallesOrdenesCompras;
    }
    
    public void setDetallesOrdenesCompras(Set<DetalleOrdenCompra> detallesOrdenesCompras) {
        this.detallesOrdenesCompras = detallesOrdenesCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenesCompra")
    public Set<Devolucion> getDevolucioneses() {
        return this.devolucioneses;
    }
    
    public void setDevolucioneses(Set<Devolucion> devolucioneses) {
        this.devolucioneses = devolucioneses;
    }




}


