package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedores generated by hbm2java
 */
@Entity
@Table(name="Proveedores"
    ,catalog="cosw2"
)
public class Proveedor  implements java.io.Serializable {


     private int idProveedores;
     private String nombre;
     private Integer telefono;
     private String direccion;
     private String pais;
     private Set<Cotizacion> cotizacioneses = new HashSet<Cotizacion>(0);
     private Set<Factura> facturases = new HashSet<Factura>(0);
     private Set<MedicamentoPorProveedor> medicamentosPorProveedors = new HashSet<MedicamentoPorProveedor>(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedores) {
        this.idProveedores = idProveedores;
    }
    public Proveedor(int idProveedores, String nombre, Integer telefono, String direccion, String pais, Set<Cotizacion> cotizacioneses, Set<Factura> facturases, Set<MedicamentoPorProveedor> medicamentosPorProveedors) {
       this.idProveedores = idProveedores;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.pais = pais;
       this.cotizacioneses = cotizacioneses;
       this.facturases = facturases;
       this.medicamentosPorProveedors = medicamentosPorProveedors;
    }
   
     @Id 

    
    @Column(name="idProveedores", unique=true, nullable=false)
    public int getIdProveedores() {
        return this.idProveedores;
    }
    
    public void setIdProveedores(int idProveedores) {
        this.idProveedores = idProveedores;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="pais", length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedores")
    public Set<Cotizacion> getCotizacioneses() {
        return this.cotizacioneses;
    }
    
    public void setCotizacioneses(Set<Cotizacion> cotizacioneses) {
        this.cotizacioneses = cotizacioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedores")
    public Set<Factura> getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set<Factura> facturases) {
        this.facturases = facturases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedores")
    public Set<MedicamentoPorProveedor> getMedicamentosPorProveedors() {
        return this.medicamentosPorProveedors;
    }
    
    public void setMedicamentosPorProveedors(Set<MedicamentoPorProveedor> medicamentosPorProveedors) {
        this.medicamentosPorProveedors = medicamentosPorProveedors;
    }




}


