package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facturas generated by hbm2java
 */
@Entity
@Table(name="Facturas"
    ,catalog="cosw2"
)
public class Factura  implements java.io.Serializable {


     private int idFacturas;
     private Proveedor proveedores;
     private Integer costo;
     private Date fecha;
     private BigDecimal usd;
     private Set<ItemDeFactura> itemsDeFacturas = new HashSet<ItemDeFactura>(0);

    public Factura() {
    }

	
    public Factura(int idFacturas) {
        this.idFacturas = idFacturas;
    }
    public Factura(int idFacturas, Proveedor proveedores, Integer costo, Date fecha, BigDecimal usd, Set<ItemDeFactura> itemsDeFacturas) {
       this.idFacturas = idFacturas;
       this.proveedores = proveedores;
       this.costo = costo;
       this.fecha = fecha;
       this.usd = usd;
       this.itemsDeFacturas = itemsDeFacturas;
    }
   
     @Id 

    
    @Column(name="idFacturas", unique=true, nullable=false)
    public int getIdFacturas() {
        return this.idFacturas;
    }
    
    public void setIdFacturas(int idFacturas) {
        this.idFacturas = idFacturas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proveedor")
    public Proveedor getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedor proveedores) {
        this.proveedores = proveedores;
    }

    
    @Column(name="Costo")
    public Integer getCosto() {
        return this.costo;
    }
    
    public void setCosto(Integer costo) {
        this.costo = costo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="USD", precision=10)
    public BigDecimal getUsd() {
        return this.usd;
    }
    
    public void setUsd(BigDecimal usd) {
        this.usd = usd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facturas")
    public Set<ItemDeFactura> getItemsDeFacturas() {
        return this.itemsDeFacturas;
    }
    
    public void setItemsDeFacturas(Set<ItemDeFactura> itemsDeFacturas) {
        this.itemsDeFacturas = itemsDeFacturas;
    }




}


