package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name="Inventario"
    ,catalog="cosw2"
)
public class Inventario  implements java.io.Serializable {


     private int idInventario;
     private Date fechaActualizacion;
     private Set<DetalleInventario> detalleInventarios = new HashSet<DetalleInventario>(0);

    public Inventario() {
    }

	
    public Inventario(int idInventario, Date fechaActualizacion) {
        this.idInventario = idInventario;
        this.fechaActualizacion = fechaActualizacion;
    }
    public Inventario(int idInventario, Date fechaActualizacion, Set<DetalleInventario> detalleInventarios) {
       this.idInventario = idInventario;
       this.fechaActualizacion = fechaActualizacion;
       this.detalleInventarios = detalleInventarios;
    }
   
     @Id 

    
    @Column(name="idInventario", unique=true, nullable=false)
    public int getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(int idInventario) {
        this.idInventario = idInventario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaActualizacion", nullable=false, length=10)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inventario")
    public Set<DetalleInventario> getDetalleInventarios() {
        return this.detalleInventarios;
    }
    
    public void setDetalleInventarios(Set<DetalleInventario> detalleInventarios) {
        this.detalleInventarios = detalleInventarios;
    }




}


