package edu.eci.cosw.mappers;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallesOrdenesCompra generated by hbm2java
 */
@Entity
@Table(name="DetallesOrdenesCompra"
    ,catalog="cosw2"
)
public class DetalleOrdenCompra  implements java.io.Serializable {


     private Integer idDetallesOrdenesCompra;
     private MedicamentoPorProveedor medicamentosPorProveedor;
     private OrdenCompra ordenesCompra;
     private Integer cantidad;

    public DetalleOrdenCompra() {
    }

	
    public DetalleOrdenCompra(MedicamentoPorProveedor medicamentosPorProveedor, OrdenCompra ordenesCompra) {
        this.medicamentosPorProveedor = medicamentosPorProveedor;
        this.ordenesCompra = ordenesCompra;
    }
    public DetalleOrdenCompra(MedicamentoPorProveedor medicamentosPorProveedor, OrdenCompra ordenesCompra, Integer cantidad) {
       this.medicamentosPorProveedor = medicamentosPorProveedor;
       this.ordenesCompra = ordenesCompra;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDetallesOrdenesCompra", unique=true, nullable=false)
    public Integer getIdDetallesOrdenesCompra() {
        return this.idDetallesOrdenesCompra;
    }
    
    public void setIdDetallesOrdenesCompra(Integer idDetallesOrdenesCompra) {
        this.idDetallesOrdenesCompra = idDetallesOrdenesCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMedicamentosProveedor", nullable=false)
    public MedicamentoPorProveedor getMedicamentosPorProveedor() {
        return this.medicamentosPorProveedor;
    }
    
    public void setMedicamentosPorProveedor(MedicamentoPorProveedor medicamentosPorProveedor) {
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idOrdenesCompra", nullable=false)
    public OrdenCompra getOrdenesCompra() {
        return this.ordenesCompra;
    }
    
    public void setOrdenesCompra(OrdenCompra ordenesCompra) {
        this.ordenesCompra = ordenesCompra;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


