package edu.eci.cosw.mappers;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicamentosPorProveedor generated by hbm2java
 */
@Entity
@Table(name="MedicamentosPorProveedor"
    ,catalog="cosw2"
)
public class MedicamentoPorProveedor  implements java.io.Serializable {


     private int idMedicamentosProvedor;
     private Medicamento medicamentos;
     private Proveedor proveedores;
     private Integer precio;
     private Set devolucioneses = new HashSet(0);
     private Set itemsDeFacturas = new HashSet(0);
     private Set detallesOrdenesCompras = new HashSet(0);
     private Set detallesPedidos = new HashSet(0);
     private Set detalleInventarios = new HashSet(0);

    public MedicamentoPorProveedor() {
    }

	
    public MedicamentoPorProveedor(int idMedicamentosProvedor, Medicamento medicamentos, Proveedor proveedores) {
        this.idMedicamentosProvedor = idMedicamentosProvedor;
        this.medicamentos = medicamentos;
        this.proveedores = proveedores;
    }
    public MedicamentoPorProveedor(int idMedicamentosProvedor, Medicamento medicamentos, Proveedor proveedores, Integer precio, Set devolucioneses, Set itemsDeFacturas, Set detallesOrdenesCompras, Set detallesPedidos, Set detalleInventarios) {
       this.idMedicamentosProvedor = idMedicamentosProvedor;
       this.medicamentos = medicamentos;
       this.proveedores = proveedores;
       this.precio = precio;
       this.devolucioneses = devolucioneses;
       this.itemsDeFacturas = itemsDeFacturas;
       this.detallesOrdenesCompras = detallesOrdenesCompras;
       this.detallesPedidos = detallesPedidos;
       this.detalleInventarios = detalleInventarios;
    }
   
     @Id 

    
    @Column(name="idMedicamentosProvedor", unique=true, nullable=false)
    public int getIdMedicamentosProvedor() {
        return this.idMedicamentosProvedor;
    }
    
    public void setIdMedicamentosProvedor(int idMedicamentosProvedor) {
        this.idMedicamentosProvedor = idMedicamentosProvedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMedicamentos", nullable=false)
    public Medicamento getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Medicamento medicamentos) {
        this.medicamentos = medicamentos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProveedores", nullable=false)
    public Proveedor getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedor proveedores) {
        this.proveedores = proveedores;
    }

    
    @Column(name="Precio")
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set getDevolucioneses() {
        return this.devolucioneses;
    }
    
    public void setDevolucioneses(Set devolucioneses) {
        this.devolucioneses = devolucioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set getItemsDeFacturas() {
        return this.itemsDeFacturas;
    }
    
    public void setItemsDeFacturas(Set itemsDeFacturas) {
        this.itemsDeFacturas = itemsDeFacturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set getDetallesOrdenesCompras() {
        return this.detallesOrdenesCompras;
    }
    
    public void setDetallesOrdenesCompras(Set detallesOrdenesCompras) {
        this.detallesOrdenesCompras = detallesOrdenesCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set getDetallesPedidos() {
        return this.detallesPedidos;
    }
    
    public void setDetallesPedidos(Set detallesPedidos) {
        this.detallesPedidos = detallesPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set getDetalleInventarios() {
        return this.detalleInventarios;
    }
    
    public void setDetalleInventarios(Set detalleInventarios) {
        this.detalleInventarios = detalleInventarios;
    }




}


