package edu.eci.cosw.mappers;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medicamentos generated by hbm2java
 */
@Entity
@Table(name="Medicamentos"
    ,catalog="cosw2"
)
public class Medicamento  implements java.io.Serializable {


     private int idMedicamentos;
     private Autorizacion autorizaciones;
     private String nombre;
     private String descripcion;
     private String presentacion;
     private Date fechaExpedicion;
     private Date fechaVencimiento;
     private Set medicamentosPorProveedors = new HashSet(0);
     private Set cotizacioneses = new HashSet(0);

    public Medicamento() {
    }

	
    public Medicamento(int idMedicamentos, Autorizacion autorizaciones) {
        this.idMedicamentos = idMedicamentos;
        this.autorizaciones = autorizaciones;
    }
    public Medicamento(int idMedicamentos, Autorizacion autorizaciones, String nombre, String descripcion, String presentacion, Date fechaExpedicion, Date fechaVencimiento, Set medicamentosPorProveedors, Set cotizacioneses) {
       this.idMedicamentos = idMedicamentos;
       this.autorizaciones = autorizaciones;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.presentacion = presentacion;
       this.fechaExpedicion = fechaExpedicion;
       this.fechaVencimiento = fechaVencimiento;
       this.medicamentosPorProveedors = medicamentosPorProveedors;
       this.cotizacioneses = cotizacioneses;
    }
   
     @Id 

    
    @Column(name="idMedicamentos", unique=true, nullable=false)
    public int getIdMedicamentos() {
        return this.idMedicamentos;
    }
    
    public void setIdMedicamentos(int idMedicamentos) {
        this.idMedicamentos = idMedicamentos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Autorizaciones_numero", nullable=false)
    public Autorizacion getAutorizaciones() {
        return this.autorizaciones;
    }
    
    public void setAutorizaciones(Autorizacion autorizaciones) {
        this.autorizaciones = autorizaciones;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="presentacion", length=45)
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaExpedicion", length=10)
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaVencimiento", length=10)
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentos")
    public Set getMedicamentosPorProveedors() {
        return this.medicamentosPorProveedors;
    }
    
    public void setMedicamentosPorProveedors(Set medicamentosPorProveedors) {
        this.medicamentosPorProveedors = medicamentosPorProveedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentos")
    public Set getCotizacioneses() {
        return this.cotizacioneses;
    }
    
    public void setCotizacioneses(Set cotizacioneses) {
        this.cotizacioneses = cotizacioneses;
    }




}


